name: CI & CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to TCR
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
            HUGO_BASEURL=https://hbs-cn.razonyang.com/
          tags: ccr.ccs.tencentyun.com/razonyang/hugo-theme-bootstrap:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      - 
        name: Deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout restart deployment -n hugo-theme-bootstrap hugo-theme-bootstrap
      - 
        name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/hugo-theme-bootstrap -n hugo-theme-bootstrap
